# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "uas" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages =[ ];

    fileSystems."/" = 
      { device = "/dev/disk/by-uuid/3d7d12f6-96ab-4d4c-bdea-ce181fcd0a50";
        fsType = "ext4";
      };

    fileSystems."/mnt/hdd/volumes" =
      { device = "/dev/disk/by-uuid/7246680c-5060-4166-9e05-d09b135282e8";
        fsType = "btrfs";
        options = [ "subvol=volumes" "compress=zstd:6" ];
      };

    fileSystems."/mnt/ssd/volumes" =
      { device = "/dev/disk/by-uuid/bba3d297-6b13-471d-8bf8-33dbd73f6d77";
        fsType = "btrfs";
        options = [ "subvol=volumes" "compress=zstd:3" ];
      };

    fileSystems."/mnt/ssd/config" =
      { device = "/dev/disk/by-uuid/bba3d297-6b13-471d-8bf8-33dbd73f6d77";
        fsType = "btrfs";
        options = [ "subvol=config" "compress=zstd:3" ];
      };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}