# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "virtio_scsi" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ef647a29-daa0-44f5-8936-f929b9af33e6";
      fsType = "ext4";
    };

  fileSystems."/snap/core18/2855" =
    { device = "/var/lib/snapd/snaps/core18_2855.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/oracle-cloud-agent/72" =
    { device = "/var/lib/snapd/snaps/oracle-cloud-agent_72.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/oracle-cloud-agent/94" =
    { device = "/var/lib/snapd/snaps/oracle-cloud-agent_94.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/snapd/23771" =
    { device = "/var/lib/snapd/snaps/snapd_23771.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/4002-4EAA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}